name: repro
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  repro-on-ubuntu:
    name: cargo run on ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Rust
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - run: cargo run